### ISSUE TITLE
so5Rewards missing?

### ISSUE THREAD

**Issue by arik555** [sorare/api#107]
![image](https://user-images.githubusercontent.com/26118556/152745693-3a870ba8-5e2e-4ae3-a9c5-8d5edb07f358.png)
Why is the rewards missing?

**Comment by redox** [comment]
Ah yes, this one is tricky but it's because a So5Reward has either cards or ETH; and since here the rank 1 has both 0.6 ETH and 1 limited star; there are actually 2 So5Reward:

The one you identified with 0.6 ETH (added `weiAmount`):
```gql
  so5Reward(slug: "28-jan-1-feb-global-all_star-division-5-rank-1") {
    id
    slug
    rewardCards {
      card {
        slug
      }
    },
    weiAmount
  }
```

and

And the one with the card:
```gql
so5Reward(slug: "28-jan-1-feb-global-all_star-division-5-rank-1-f3389aa3-fc7c-4906-a1db-7bafdb255521") {
    id
    slug
    rewardCards {
      card {
        slug
      }
    },
    weiAmount
  }
```

I'm going to check whether it's possible to add an extra `ranking` arg to `so5Rewards` so it's easier to get all So5Rewards at a specific rank:

```gql
query {
	so5Leaderboard(slug: "28-jan-1-feb-global-all_star-division-5") {
  	so5Rewards {
      nodes {
        slug
        so5Ranking {
          ranking
        }
        rewardCards {
          card {
            id
          }
        }
        weiAmount
      }
    }
  }
}
```
