### ISSUE TITLE
Get receiverLimitOrder of liveSingleSaleOffer in subscription

### ISSUE THREAD

**Issue by arctcpk** [sorare/api#113]
Hi all,

Is there any option to get the `receiverLimitOrder` of a `liveSingleSaleOffer` in the `aCardWasUpdated` subscription, or another websocket subscription? I understand that per the docs this is marked as deprecated and that we are supposed to use the `prepareAcceptOffer` mutation instead. It would be nice to avoid the additional API call though.

Thanks in advance for your help, I appreciate it!

**Comment by redox** [comment]
Hi @arctcpk ,

> I understand that per the docs this is marked as deprecated and that we are supposed to use the `prepareAcceptOffer` mutation instead.

Yes correct.

> I understand that per the docs this is marked as deprecated and that we are supposed to use the `prepareAcceptOffer` mutation instead.

Indeed, same for the `prepareOffer` mutation whenever you create an offer.

> It would be nice to avoid the additional API call though.

Unfortunately, we are moving away from such a "1 API call to do it all" (especially within Subscriptions) as it really doesn't provide much flexibility on anything that can do wrong under the hood while creating the limit orders, including dealing with error messages.

You'll need to perform extra API call in order to do this.

I'll also update the docs, as it's still relying on the recently deprecated `receiverLimitOrders`.
