### ISSUE TITLE
so5Rewards minting??

### ISSUE THREAD

**Issue by arik555** [sorare/api#117]
When a gameweek is complete, after how many days or hours, we can get all the 100% distributed cards for the reward winners, for every league & leaderboards.?

**Comment by redox** [comment]
Hi @arik555,

I don't think we want to communicate/commit on such ETA for now. What are you trying to achieve?

**Comment by arik555** [comment]
@redox I am trying to achieve the reward_cards for every leaderboard in a gameweek.
But sometimes, I get no reward cards.
For example, 
![image](https://user-images.githubusercontent.com/26118556/153833984-58ef5c4b-acc9-43a4-be46-226ac852a313.png)

**Comment by redox** [comment]
> But sometimes, I get no reward cards.

Well, as shared in https://github.com/sorare/api/issues/107 this is not because the cards a missing, it's because the object you're looking at is the ETH reward: add also `weiAmount` next to `rewardCards` to see it.

If you iterate over the whole list, you'll see there will be 2 `So5Reward` object for the rank who are getting ETH + Cards.

```gql
query {
  so5Leaderboard(slug: "8-11-feb-champion-europe-division-1") {
    so5Rewards {
      nodes {
        id
        slug
        rewardCards {
          card {
            slug
          }
        }
        weiAmount
        so5Ranking {
          ranking
          score
        }
      }
    }
  }
}
```
