### ISSUE TITLE
Subscriptions ends after 2 hours with connection reset by peer

### ISSUE THREAD

**Issue by jensvandenwyenbergh** [sorare/api#139]
I'am using the python example to query the subscriptions.
After 2 hours I get a reset by peer error.

	"metadata": {
			"outputType": "error",
			"originalError": {
				"ename": "ConnectionResetError",
				"evalue": "[Errno 54] Connection reset by peer",
				"output_type": "error",
				"traceback": [
					"\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
					"\u001b[0;31mConnectionResetError\u001b[0m                      Traceback (most recent call last)",

**Comment by Moreas** [comment]
This issue is closed but I am facing the same problem and would like to handle it properly like you suggest.
I am now checking every 2 hours to close and reopen the WebSocket.
I guess there is a better way to do that, especially if you intend to reduce this time in the future
My problem is that there does not seem to be any error catched by the python code when the "reset by peer" error happens. It just seems to stop without notification. 
Is this the expected behavior? 
How can I grab the information that the connexion has been reset on your side so I can reconnect properly?
Thanks
