### ISSUE TITLE
field transferType - incorrect value for Bundles

### ISSUE THREAD

**Issue by mbh86** [sorare/api#197]
Hello,

I noticed that some players from Serie A have an incorrect transferType. It returns `auction` instead of `bundled_auction`.

```
{
  card(slug: "alvaro-borja-morata-martin-2021-limited-275") {
    slug
    notContractOwners {
      from
      transferType
    }
  }
}
```

returns

```
{
  "data": {
    "card": {
      "slug": "alvaro-borja-morata-martin-2021-limited-275",
      "notContractOwners": [
        {
          "from": "2022-03-27T17:13:59Z",
          "transferType": "auction"
        },
        {
          "from": "2022-03-31T18:41:47Z",
          "transferType": "single_sale_offer"
        }
      ]
    }
  }
}
```

**Comment by BrainTR** [comment]
I don't know if this issue will ever be fixed. But i found a way to detect if a card sold with a bundle.
Use the query below. If card.latestEnglishAuction.cards field has more then one item then its a bundle sale.
```
{
  card(slug: "alvaro-borja-morata-martin-2021-limited-275") {
    slug
    latestEnglishAuction {
      cards {
        slug
      }
    }
  }
}
```
returns
```
{
  "data": {
    "card": {
      "slug": "alvaro-borja-morata-martin-2021-limited-275",
      "latestEnglishAuction": {
        "cards": [
          {
            "slug": "alvaro-borja-morata-martin-2021-limited-275"
          },
          {
            "slug": "mattia-perin-2021-limited-270"
          },
          {
            "slug": "adrien-rabiot-2021-limited-263"
          },
          {
            "slug": "dusan-vlahovic-2021-limited-29"
          },
          {
            "slug": "paulo-bruno-exequiel-dybala-2021-limited-268"
          }
        ]
      }
    }
  }
}
```

**Comment by eulbat** [comment]
As mentioned, you can count the number of cards in the auction to know if it was sold as a bundle or not.
What's your use case for this and why do you need this granularity?

**Comment by juliusdanek** [comment]
I am not using the Auction object, I am using the notContractOwners object. You cannot count the cards in there.

I need to know since the price_eth that you guys display is wrong in the notContractOwners object but now (unlike before) I have no way of differentiating between a normal auction and a bundled auction, which means I don't know which prices are right and which ones are wrong...

**Comment by juliusdanek** [comment]
@eulbat can you let me know? Getting this right is very important for getting clean data from your API and a departure from data that was historically relied upon and changed without notice. 

PS: You can just solve this easily by adding the unique ID for the transfer (https://github.com/sorare/api/issues/209).

**Comment by eulbat** [comment]
Hey @juliusdanek 
Working on that, I'll let you know the details but it will probably also resolve #209 as you mentioned.

**Comment by juliusdanek** [comment]
That is amazing! Thank you @eulbat

**Comment by eulbat** [comment]
Now that #209 is done, the best solution would be to rely on the `referenceId` to fetch the auction and check the number of cards that were included in that auction. On our side, we don't make that distinction anymore because we consider an auction to always have a collection of cards.

Let me know if that works for you

**Comment by juliusdanek** [comment]
@eulbat I'm testing it right now but this solution should be perfectly fine!
