### ISSUE TITLE
aCardWasUpdated subscription changes not updated in change log

### ISSUE THREAD

**Issue by doublesavonette** [sorare/api#219]
Hi @eulbat 

Would you know if some fields have been removed from aCardWasUpdated today which have not been added to the change log?

My subscription was running fine up until 30 mins or so ago and now returns empty data.

Cheers

**Comment by eulbat** [comment]
Hi @doublesavonette 
could you please provide an example of the fields that are now giving you empty data?

**Comment by doublesavonette** [comment]
@eulbat Thanks for your reply. Looks like things are back now. But the stream was really patchy for the last 30 mins. I was essentially getting a completely empty data object. I mean getting no data updates from the websocket. Looks like things got sort of sorted around 3.37pm French time. 

I can close the issue unless you'd like me to post my subscription

**Comment by Tradetechnique** [comment]
Hi @doublesavonette, 
Did you have already the issue ? 
After some times of subscription execution (about 2 hours), I have this issue : 
`[WinError 10054] An existing connection was forcibly closed by the remote host`

I use this script : https://github.com/sorare/api/blob/master/examples/subscribe_all_card_updates.py

May be because I don't have an API Key ? 
Thanks
