### ISSUE TITLE
Invalid offer for SingleBuyOffer

### ISSUE THREAD

**Issue by Fabien44600** [sorare/api#365]
Hello,

I have an Invalid Offer error for a createSingleBuyOffer.
The message is {'data': {'createSingleBuyOffer': {'offer': None, 'errors': [{'message': 'Invalid offer', 'path': None, 'code': None}]}}}
There no more information about this error.
What does it mean ?

`>>> {'data': {'prepareOffer': {'limitOrders': [{'amountBuy': '1', 'amountSell': '290000', 'expirationTimestamp': 466502, 'nonce': 30147, 'tokenBuy': '0x04...', 'tokenSell': '0xb...', 'vaultIdBuy': 13805017, 'vaultIdSell': 3921735}], 'errors': []}}}
>>> {'input': {'starkSignatures': [{'data': '{"r": "0x...", "s": "0x..."}', 'nonce': 30147, 'expirationTimestamp': 466502, 'starkKey': '0x04...'}], 'dealId': "b'K\\x16\\x15\\x96\\xe7\\x84\\x98J'", 'price': 2900000000000000, 'clientMutationId': "b'\\xb6\\t\\x96\\xe8\\x06?\\xd7t'", 'assetId': '0x0400e7405725b73c987b425bd8ee24bd3ecc1d404f6b29d8a50888c01c53eaf5'}}`

Thank you

**Comment by J4F8** [comment]
Hello, isn't it because type of dealId and clientMutationId should be string and not byte ?

**Comment by Fabien44600** [comment]
Hello J4F8,
In my script, dealId and clientMutationId are string.
`variables = {
        "input" :{
            "starkSignatures" : starkSignatures,
            "dealId": str(cr.get_random_bytes(8)),
            "price": price,
            "clientMutationId": str(cr.get_random_bytes(8)),
            "assetId": asset_id
        }
    }`
This script worked before the latest update (depreciate cardSlug for assetId).

**Comment by J4F8** [comment]
Hello Fabien44600,

Same problem for me. My code was running the 16th of January but no more works since the recent API update you mentioned. Same as you: **{'data': {'createSingleBuyOffer': {'offer': None, 'errors': [{'message': 'Invalid offer'}]}}}**

https://github.com/sorare/api/blob/master/CHANGELOG.md
   Deprecated the following field from prepareOffer:
   cardSlug: use assetId

Unclear as my code was already using assetId and not cardSlug.

**New API:**
# Autogenerated input type of prepareOffer
input prepareOfferInput {
  # A unique identifier for the client performing the mutation.
  clientMutationId: String
  type: OfferType
  sendAssetIds: [String!]
  receiveAssetIds: [String!]
  sendWeiAmount: WeiAmount!
  receiveWeiAmount: WeiAmount!
  receiverSlug: String
}

**Previous API**
# Autogenerated input type of prepareOffer
input prepareOfferInput {
  # A unique identifier for the client performing the mutation.
  clientMutationId: String
  type: OfferType
  **sendCardsSlugs: [String!]**
  sendAssetIds: [String!]
  **receiveCardsSlugs: [String!]**
  receiveAssetIds: [String!]
  sendWeiAmount: WeiAmount!
  receiveWeiAmount: WeiAmount!
  receiverSlug: String
}

createSingleSaleOffer works fine.

Hello @redox , any help is welcome for this createSingleBuyOffer recent issue.

**Comment by TyRappal** [comment]
Hello, i get the same error

**Comment by J4F8** [comment]
Hello @Fabien44600, @TyRappal 
For some reason, it's now working again.

**Comment by eulbat** [comment]
Hello @Fabien44600 @J4F8 @TyRappal, I pushed a fix for this in the afternoon and forgot to notify you.
Apologies for the trouble!

Feel free to reopen if you face other related issues
