### ISSUE TITLE
Get player Slugs

### ISSUE THREAD

**Issue by rikidas** [sorare/api#85]
Hi everyone, im executing this query to extract all the players slugs, first i pick a league. then a club and themn the players slugs:
`
{
                competition(slug: "mls-us") {
                clubs {
                nodes {
                name
                slug
                activePlayers {
                nodes {
                displayName
                slug
                }
                }
                }
                }
                }
                }
`

In the past it was working but now it gives me this error: 

`"Selecting "activePlayers" within a list of "Club" ("clubs") is not supported, please select `activePlayers` for a specific "Club" instead."`

Any thoughts? Thanks

**Comment by doublesavonette** [comment]
@rikidas got the same problem through a different query. They probably made changes to their api but did not give a crap to a) inform users ahead of time b) work on backward compatibility to prevent ppls queries to crash. 

Their suggestion works. You have to iterate over clubs. glhf

**Comment by redox** [comment]
Hi @rikidas and @doublesavonette ; this is indeed a change that happened earlier this year as part of a big audit we've done.  
 This way of querying the API wasn't scaling anymore and we had to either introduce more paginated fields or forbid the nesting of some fields.

In your case, instead of getting all players for all clubs in a single query; you now need to retrieve all clubs; and then for each of them to an additional query to retrieve all players.

I'm going to add the email we sent to our APIKEY users to a CHANGELOG file for this to be cristal clear.
